const Cupon = require('../../domain/entities/cupon.entity');
const { NotFoundError } = require('../../domain/errors');

class CuponService {
    constructor(cuponRepository) { // ¡Depende de la interfaz!
        this.cuponRepository = cuponRepository;
    }
    
    async getAllCupon() {
        return this.cuponRepository.getAll();
    }

    async getCuponById(id) {
        const order = await this.cuponRepository.getById(id);
        if (!order) {
            throw new NotFoundError(`Cupon with id ${id} not found`);
        }
        return order;
    }

    async createCupon(cuponData) {
        // Aquí podría haber lógica de negocio y validaciones
        const cuponEntity = new Cupon(
            null, // ID is null because it will be generated by the database
            cuponData.code,
            cuponData.description,
            cuponData.discountPercentage,
            cuponData.validFrom,
            cuponData.validUntil            
        );
        return this.cuponRepository.create(cuponEntity);
    }

    async updateCupon(id, orderData) {
        const existingProduct = await this.cuponRepository.getById(id);
        if (!existingProduct) {
            throw new NotFoundError(`Cupon with id ${id} not found`);
        }

        const cuponEntity = new Cupon(
            id,
            uponData.code,
            cuponData.description,
            cuponData.discountPercentage,
            cuponData.validFrom,
            cuponData.validUntil
        );
        return this.cuponRepository.update(id, cuponEntity);
    }

    async deleteCupon(id) {
        const order = await this.cuponRepository.getById(id);
        if (!order) {
            throw new NotFoundError(`Cupon with id ${id} not found`);
        }
        return this.cuponRepository.delete(id);
    }
}
module.exports = CuponService;