const Order = require('../../domain/entities/order.entity');
const { NotFoundError } = require('../../domain/errors');

class OrderService {
    constructor(orderRepository) { // ¡Depende de la interfaz!
        this.orderRepository = orderRepository;
    }
    
    async getAllOrder() {
        return this.orderRepository.getAll();
    }

    async getOrderById(id) {
        const order = await this.orderRepository.getById(id);
        if (!order) {
            throw new NotFoundError(`Order with id ${id} not found`);
        }
        return order;
    }

    async createOrder(orderData) {
        // Aquí podría haber lógica de negocio y validaciones
        const orderEntity = new Order(
            null, // ID is null because it will be generated by the database
            orderData.orderNumber,
            orderData.userId,
            orderData.creationDate,
            orderData.updateDate,
            orderData.status,
            orderData.totalAmount
        );
        return this.orderRepository.create(orderEntity);
    }

    async updateOrder(id, orderData) {
        const existingProduct = await this.orderRepository.getById(id);
        if (!existingProduct) {
            throw new NotFoundError(`Order with id ${id} not found`);
        }

        const orderEntity = new Order(
            id,
            orderData.orderNumber,
            orderData.userId,
            orderData.creationDate,
            orderData.updateDate,
            orderData.status,
            orderData.totalAmount
        );
        return this.orderRepository.update(id, orderEntity);
    }

    async deleteOrder(id) {
        const order = await this.orderRepository.getById(id);
        if (!order) {
            throw new NotFoundError(`Order with id ${id} not found`);
        }
        return this.orderRepository.delete(id);
    }
}
module.exports = OrderService;